version: '3'

services:
  api:
    build: .
    container_name: expenses-api
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
    volumes:
      - .:/usr/src/app
    networks:
      - expenses-network
    command: ./wait-for.sh db:27017 -- npm run dev
  db:
    image: mongo:4.4.0-bionic
    container_name: expenses-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:  
      - "dbdata:/data/db"
    networks:
      - expenses-network    

networks:
  expenses-network:
    driver: bridge
      
volumes:
  dbdata: